# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test
    
    - name: Archive code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage/lcov-report/index.html
